name: tesla
description: "Tesla App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_neumorphic_plus: ^3.3.0
  flutter_svg: ^2.0.10+1
  animated_bottom_navigation_bar: ^1.3.3
  d_navigation_bar: ^0.0.1
  sleek_circular_slider: ^2.0.1
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
